# Ref :: https://pre-commit.com/#adding-pre-commit-plugins-to-your-project
fail_fast: true
minimum_pre_commit_version: 3.0.0
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.1
    hooks:
      - name: Terraform Lock Provider
        id: terraform_providers_lock
        args:
          - --args=-platform=windows_amd64
          - --args=-platform=darwin_amd64

      - id: tfupdate
        name: Autoupdate Terraform versions

      - name: Terraform Validation
        id: terraform_validate
        args:
          - --hook-config=--retry-once-with-cleanup=true

      - name: Terraform Format
        id: terraform_fmt

      - name: Terraform Lint with 'tflint'
        id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl

      # - name: Terraform Scan with 'tfsec'
      #   id: terraform_tfsec

      - name: Terraform Documentation
        id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
